name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.0,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          echo "1st Script Executing"
#         env: 
#          destination: ${{ matrix.destination }}
